spring:
  application:
    name: student-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: *
    username: *
    password: *
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  data:
    redis:
      host: *
      port: *
      database: 2
      password: *
      timeout: 10000ms
      lettuce:
        pool:
          min-idle: 8
          max-idle: 12
          max-active: 50
          max-wait: 5000ms
server:
  servlet:
    context-path: /api
    multipart:
      enabled: true
  undertow:
    max-http-post-size: -1
    buffer-size: 512
    direct-buffers: true
    threads:
      io: 8
      worker: 256
  port: 8768
token:
  header: AuthToken
  secret: DQ@d4w@%%F!@#wFa1ad!D#$Gugle@%aa51f45f45a5%asa#!$F
